from typing import Protocol, List
from ..domain.entities import Ticket

class TicketRepository(Protocol):
    def add(self, ticket: Ticket) -> None: ...
    def remove(self, ticket_id: str) -> None: ...
    def get_all(self) -> List[Ticket]: ...